# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "uas" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelParams = ["fbcon=font:VGA8x16" "default_hugepagesz=2M" "hugepagesz=1G" "hugepages=3"];
  #boot.kernelParams = ["fbcon=font:VGA8x16"] ;
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
	#boot.resumeDevice = "/dev/disk/by-uuid/c26a149b-94bf-4585-90da-e3ac33f628ee";
	#boot.kernelParams = [ "resume=/dev/disk/by-uuid/c26a149b-94bf-4585-90da-e3ac33f628ee" "resume_offset=133847040" ];

  fileSystems."/" =
    { device = "/dev/nvme0n1p4";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/nvme0n1p1";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
  #swapDevices =[{ 
	#		device = "/swapfile"; 
	#		size = 40 * 1024;
  #  }];  


  #swapDevices =
  #  [ { device = "/dev/disk/by-uuid/a600a7b0-be8e-4416-b432-1ee4099da312"; }
  #  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
